#pragma once

//glfw3.h
#define MONSI_MOUSE_BUTTON_1         0
#define MONSI_MOUSE_BUTTON_2         1
#define MONSI_MOUSE_BUTTON_3         2
#define MONSI_MOUSE_BUTTON_4         3
#define MONSI_MOUSE_BUTTON_5         4
#define MONSI_MOUSE_BUTTON_6         5
#define MONSI_MOUSE_BUTTON_7         6
#define MONSI_MOUSE_BUTTON_8         7
#define MONSI_MOUSE_BUTTON_LAST      MONSI_MOUSE_BUTTON_8
#define MONSI_MOUSE_BUTTON_LEFT      MONSI_MOUSE_BUTTON_1
#define MONSI_MOUSE_BUTTON_RIGHT     MONSI_MOUSE_BUTTON_2
#define MONSI_MOUSE_BUTTON_MIDDLE    MONSI_MOUSE_BUTTON_3