#pragma once

//glfw3.h
#define MONSI_GAMEPAD_BUTTON_A               0
#define MONSI_GAMEPAD_BUTTON_B               1
#define MONSI_GAMEPAD_BUTTON_X               2
#define MONSI_GAMEPAD_BUTTON_Y               3
#define MONSI_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define MONSI_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define MONSI_GAMEPAD_BUTTON_BACK            6
#define MONSI_GAMEPAD_BUTTON_START           7
#define MONSI_GAMEPAD_BUTTON_GUIDE           8
#define MONSI_GAMEPAD_BUTTON_LEFT_THUMB      9
#define MONSI_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define MONSI_GAMEPAD_BUTTON_DPAD_UP         11
#define MONSI_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define MONSI_GAMEPAD_BUTTON_DPAD_DOWN       13
#define MONSI_GAMEPAD_BUTTON_DPAD_LEFT       14
#define MONSI_GAMEPAD_BUTTON_LAST            MONSI_GAMEPAD_BUTTON_DPAD_LEFT